// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: protoql/v1/service.proto

package transportv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecuteRequest describes one or more operations; the POC accepts exactly one query.
type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queries       []*Operation           `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	Mutations     []*Operation           `protobuf:"bytes,2,rep,name=mutations,proto3" json:"mutations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_protoql_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoql_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_protoql_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetQueries() []*Operation {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *ExecuteRequest) GetMutations() []*Operation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

type Operation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Root GraphQL field name (e.g. "customers", "products").
	Name       string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parameters []*Parameter `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
	// Projection shape — drives dynamic response descriptor and payload.
	Result        []*ResultField `protobuf:"bytes,3,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_protoql_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_protoql_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_protoql_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *Operation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Operation) GetParameters() []*Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Operation) GetResult() []*ResultField {
	if x != nil {
		return x.Result
	}
	return nil
}

type Parameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	mi := &file_protoql_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_protoql_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_protoql_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *Parameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Parameter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ResultField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parser        *string                `protobuf:"bytes,2,opt,name=parser,proto3,oneof" json:"parser,omitempty"`
	Children      []*ResultField         `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultField) Reset() {
	*x = ResultField{}
	mi := &file_protoql_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultField) ProtoMessage() {}

func (x *ResultField) ProtoReflect() protoreflect.Message {
	mi := &file_protoql_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultField.ProtoReflect.Descriptor instead.
func (*ResultField) Descriptor() ([]byte, []int) {
	return file_protoql_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ResultField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResultField) GetParser() string {
	if x != nil && x.Parser != nil {
		return *x.Parser
	}
	return ""
}

func (x *ResultField) GetChildren() []*ResultField {
	if x != nil {
		return x.Children
	}
	return nil
}

type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protobuf wire encoding of the first projected row.
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// Serialized google.protobuf.FileDescriptorSet for decoding payload.
	FileDescriptorSet []byte `protobuf:"bytes,2,opt,name=file_descriptor_set,json=fileDescriptorSet,proto3" json:"file_descriptor_set,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_protoql_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoql_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_protoql_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteResponse) GetFileDescriptorSet() []byte {
	if x != nil {
		return x.FileDescriptorSet
	}
	return nil
}

var File_protoql_v1_service_proto protoreflect.FileDescriptor

const file_protoql_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x18protoql/v1/service.proto\x12\n" +
	"protoql.v1\"v\n" +
	"\x0eExecuteRequest\x12/\n" +
	"\aqueries\x18\x01 \x03(\v2\x15.protoql.v1.OperationR\aqueries\x123\n" +
	"\tmutations\x18\x02 \x03(\v2\x15.protoql.v1.OperationR\tmutations\"\x87\x01\n" +
	"\tOperation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2\x15.protoql.v1.ParameterR\n" +
	"parameters\x12/\n" +
	"\x06result\x18\x03 \x03(\v2\x17.protoql.v1.ResultFieldR\x06result\"5\n" +
	"\tParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"~\n" +
	"\vResultField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\x06parser\x18\x02 \x01(\tH\x00R\x06parser\x88\x01\x01\x123\n" +
	"\bchildren\x18\x03 \x03(\v2\x17.protoql.v1.ResultFieldR\bchildrenB\t\n" +
	"\a_parser\"[\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12.\n" +
	"\x13file_descriptor_set\x18\x02 \x01(\fR\x11fileDescriptorSet2M\n" +
	"\aProtoQL\x12B\n" +
	"\aExecute\x12\x1a.protoql.v1.ExecuteRequest\x1a\x1b.protoql.v1.ExecuteResponseBBZ@github.com/samuelfabel/protoql/internal/transport/v1;transportv1b\x06proto3"

var (
	file_protoql_v1_service_proto_rawDescOnce sync.Once
	file_protoql_v1_service_proto_rawDescData []byte
)

func file_protoql_v1_service_proto_rawDescGZIP() []byte {
	file_protoql_v1_service_proto_rawDescOnce.Do(func() {
		file_protoql_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoql_v1_service_proto_rawDesc), len(file_protoql_v1_service_proto_rawDesc)))
	})
	return file_protoql_v1_service_proto_rawDescData
}

var file_protoql_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protoql_v1_service_proto_goTypes = []any{
	(*ExecuteRequest)(nil),  // 0: protoql.v1.ExecuteRequest
	(*Operation)(nil),       // 1: protoql.v1.Operation
	(*Parameter)(nil),       // 2: protoql.v1.Parameter
	(*ResultField)(nil),     // 3: protoql.v1.ResultField
	(*ExecuteResponse)(nil), // 4: protoql.v1.ExecuteResponse
}
var file_protoql_v1_service_proto_depIdxs = []int32{
	1, // 0: protoql.v1.ExecuteRequest.queries:type_name -> protoql.v1.Operation
	1, // 1: protoql.v1.ExecuteRequest.mutations:type_name -> protoql.v1.Operation
	2, // 2: protoql.v1.Operation.parameters:type_name -> protoql.v1.Parameter
	3, // 3: protoql.v1.Operation.result:type_name -> protoql.v1.ResultField
	3, // 4: protoql.v1.ResultField.children:type_name -> protoql.v1.ResultField
	0, // 5: protoql.v1.ProtoQL.Execute:input_type -> protoql.v1.ExecuteRequest
	4, // 6: protoql.v1.ProtoQL.Execute:output_type -> protoql.v1.ExecuteResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protoql_v1_service_proto_init() }
func file_protoql_v1_service_proto_init() {
	if File_protoql_v1_service_proto != nil {
		return
	}
	file_protoql_v1_service_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoql_v1_service_proto_rawDesc), len(file_protoql_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoql_v1_service_proto_goTypes,
		DependencyIndexes: file_protoql_v1_service_proto_depIdxs,
		MessageInfos:      file_protoql_v1_service_proto_msgTypes,
	}.Build()
	File_protoql_v1_service_proto = out.File
	file_protoql_v1_service_proto_goTypes = nil
	file_protoql_v1_service_proto_depIdxs = nil
}
