// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: protoql/v1/service.proto

package transportv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProtoQL_Execute_FullMethodName = "/protoql.v1.ProtoQL/Execute"
)

// ProtoQLClient is the client API for ProtoQL service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProtoQL is the POC gRPC service: GraphQL document in, projection bytes out.
type ProtoQLClient interface {
	// Execute compiles the query, projects in-memory fixtures, and returns
	// wire bytes plus the FileDescriptorSet for the same projection.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
}

type protoQLClient struct {
	cc grpc.ClientConnInterface
}

func NewProtoQLClient(cc grpc.ClientConnInterface) ProtoQLClient {
	return &protoQLClient{cc}
}

func (c *protoQLClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, ProtoQL_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtoQLServer is the server API for ProtoQL service.
// All implementations must embed UnimplementedProtoQLServer
// for forward compatibility.
//
// ProtoQL is the POC gRPC service: GraphQL document in, projection bytes out.
type ProtoQLServer interface {
	// Execute compiles the query, projects in-memory fixtures, and returns
	// wire bytes plus the FileDescriptorSet for the same projection.
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	mustEmbedUnimplementedProtoQLServer()
}

// UnimplementedProtoQLServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProtoQLServer struct{}

func (UnimplementedProtoQLServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedProtoQLServer) mustEmbedUnimplementedProtoQLServer() {}
func (UnimplementedProtoQLServer) testEmbeddedByValue()                 {}

// UnsafeProtoQLServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProtoQLServer will
// result in compilation errors.
type UnsafeProtoQLServer interface {
	mustEmbedUnimplementedProtoQLServer()
}

func RegisterProtoQLServer(s grpc.ServiceRegistrar, srv ProtoQLServer) {
	// If the following call pancis, it indicates UnimplementedProtoQLServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProtoQL_ServiceDesc, srv)
}

func _ProtoQL_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoQLServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtoQL_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoQLServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProtoQL_ServiceDesc is the grpc.ServiceDesc for ProtoQL service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProtoQL_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protoql.v1.ProtoQL",
	HandlerType: (*ProtoQLServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _ProtoQL_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoql/v1/service.proto",
}
