// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protoql/v1/service.proto

package transportv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GraphQL query document (single query operation).
	Query         string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_protoql_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoql_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_protoql_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protobuf wire encoding of the first projected row.
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// Serialized google.protobuf.FileDescriptorSet for decoding payload.
	FileDescriptorSet []byte `protobuf:"bytes,2,opt,name=file_descriptor_set,json=fileDescriptorSet,proto3" json:"file_descriptor_set,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_protoql_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoql_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_protoql_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteResponse) GetFileDescriptorSet() []byte {
	if x != nil {
		return x.FileDescriptorSet
	}
	return nil
}

var File_protoql_v1_service_proto protoreflect.FileDescriptor

const file_protoql_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x18protoql/v1/service.proto\x12\n" +
	"protoql.v1\"&\n" +
	"\x0eExecuteRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"[\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12.\n" +
	"\x13file_descriptor_set\x18\x02 \x01(\fR\x11fileDescriptorSet2M\n" +
	"\aProtoQL\x12B\n" +
	"\aExecute\x12\x1a.protoql.v1.ExecuteRequest\x1a\x1b.protoql.v1.ExecuteResponseBBZ@github.com/samuelfabel/protoql/internal/transport/v1;transportv1b\x06proto3"

var (
	file_protoql_v1_service_proto_rawDescOnce sync.Once
	file_protoql_v1_service_proto_rawDescData []byte
)

func file_protoql_v1_service_proto_rawDescGZIP() []byte {
	file_protoql_v1_service_proto_rawDescOnce.Do(func() {
		file_protoql_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoql_v1_service_proto_rawDesc), len(file_protoql_v1_service_proto_rawDesc)))
	})
	return file_protoql_v1_service_proto_rawDescData
}

var file_protoql_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protoql_v1_service_proto_goTypes = []any{
	(*ExecuteRequest)(nil),  // 0: protoql.v1.ExecuteRequest
	(*ExecuteResponse)(nil), // 1: protoql.v1.ExecuteResponse
}
var file_protoql_v1_service_proto_depIdxs = []int32{
	0, // 0: protoql.v1.ProtoQL.Execute:input_type -> protoql.v1.ExecuteRequest
	1, // 1: protoql.v1.ProtoQL.Execute:output_type -> protoql.v1.ExecuteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoql_v1_service_proto_init() }
func file_protoql_v1_service_proto_init() {
	if File_protoql_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoql_v1_service_proto_rawDesc), len(file_protoql_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoql_v1_service_proto_goTypes,
		DependencyIndexes: file_protoql_v1_service_proto_depIdxs,
		MessageInfos:      file_protoql_v1_service_proto_msgTypes,
	}.Build()
	File_protoql_v1_service_proto = out.File
	file_protoql_v1_service_proto_goTypes = nil
	file_protoql_v1_service_proto_depIdxs = nil
}
